[tool.poetry]
name = "algovis"
version = "0.1.0001"
description = "README.md"
authors = ["hotshot07 <aroram@tcd.ie>"]

[tool.poetry.dependencies]
python = "^3.7.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
